runtime: java
env: flex

handlers:
  - url: /.*
    script: this field is required, but ignored

manual_scaling:
  instances: 1

runtime_config:
  jdk: openjdk8
  server: jetty9

env_variables:
  JAVA_TOOL_OPTIONS: "-Xms256m -Xmx512m"
  # Các biến môi trường khác nếu cần

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  cool_down_period_sec: 60
